# If you experience problems with the CKAN container not being
# able to connect to the DB, then most likely the DB has not
# started up quickly enough. Just do "docker-compose up ckan"
# again to retry

version: '3.8'
services:
  ckan:
    image: ckan
    build: ../.
    networks:
        - sub
        - db
        - sparql
    expose:
       - "5000"
    environment:
       CKAN_DATASTORE_WRITE: "postgresql://ckan:ckan@postgresql:5432/datastore_default"
       CKAN_DATASTORE_READ: "postgresql://datastore_default:datastore@postgresql:5432/datastore_default"
       CKAN_PUSHER_URL: "http://pusher:8800"
       CKAN_REDIS_URL: "redis://redis:6379/0"
       CKAN_SITE_URL: "https://${BASE_DOMAIN}"
       CKAN_SOLR_URL: "http://solr:8983/solr/ckan"
       CKAN_SQLALCHEMY_URL: "postgresql://ckan:ckan@postgresql:5432/ckan"
       CKAN_EXT_DATARETRIEVAL: "http://dataretrieval:8080"
       VIRTUAL_HOST: "${BASE_DOMAIN}"
       VIRTUAL_PORT: "5000"
       LETSENCRYPT_HOST: "${BASE_DOMAIN}"
  postgresql:
    build: ./postgresql-loaded/
    image: postgresql:loaded
    networks:
        - db
    expose:
        - "5432"
  solr:
    build: ./solr/
    image: fhg/solr
    networks:
        - db
    expose:
        - "8983"
  redis:
    image: redis
    networks:
        - db
    expose:
        - "6379"
  pusher:
    image: easyckan/ckan-datapusher:2.6
    networks:
        - db
    expose:
        - "8800"
  postfix:
    image: tozd/postfix:ubuntu-trusty
    expose:
      - "25"
    networks:
      - sub
      - db
  dataretrieval:
      image: docker.pkg.github.com/aksw/service-dataretrieval/dataretrieval:main
      expose:
          - "8080"
      environment:
          SPARQL_URL: "http://virtuoso:8890/sparql"
          SPARQL_USERNAME: "${VIRTUOSO_USER}"
          SPARQL_PASSWORD: "${VIRTUOSO_PASSWORD}"
          SPARQL_PORT: "8890"
          VIRTUAL_HOST: "dataretrieval.${BASE_DOMAIN}"
          VIRTUAL_PORT: "8080"
          LETSENCRYPT_HOST: "dataretrieval.${BASE_DOMAIN}"
      networks:
          - sparql
          - sub
  virtuoso:
    image: openlink/virtuoso-opensource-7
    expose:
        - "8890"
    environment:
        DBA_PASSWORD: "${VIRTUOSO_PASSWORD}"
        VIRTUAL_HOST: "sparql.${BASE_DOMAIN}"
        VIRTUAL_PORT: "8890"
        LETSENCRYPT_HOST: "sparql.${BASE_DOMAIN}"
    networks:
        - sparql
        - sub
      
networks:
    db: 
    sparql: 
    sub: 
       external:
          name: stream_sub
